### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by alidabaghi123** [k2-fsa/icefall#1139]
"Sorry, no matter how much I studied the code, I couldn't exactly understand what the max_duration part does. Can you guide me?" It appears that based on your intuition, it seems that padding operations are being performed.

**Comment by csukuangfj** [comment]
Please search for `max_duration` in
https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/sampling/base.py

**Comment by npovey** [comment]
Hi @alidabaghi123,
I made a podcast with Dan and at some point he mentioned max_duration. here the article:
https://medium.com/@nadirapovey/k2fsa-audio-segmentation-c7b35893ed50 here is the video https://www.youtube.com/watch?v=uVCyhdF5oC0&ab_channel=NadiraPovey
In short:
Q4: In [run.sh](https://github.com/k2-fsa/text_search/blob/master/examples/libriheavy/run.sh), you have “ — max-duration 2400”, but when we did max duration, 2,400 it said there wasn’t enough space on our GPU to handle that. So we decreased it to 240 and it worked. Can you explain what decreasing it would do?
So the max duration is the total number of seconds in the batch because it’s recognizing in batches. On GPUs, it’s important to batch everything up because that’s how GPUs are fast by batching stuff. So the GPUs that we ran this on have 32 gigabytes of memory and most likely yours have less. So let’s suppose you have 16 gigabytes. You should probably set that to 1200 or a bit less because the model itself adds a certain fixed amount. So probably 1000 would have worked for you.

Hope it helps.
