### ISSUE TITLE
shared/make_kn_gram.py Error when sum_z1_f_z equals (or overflows to) 1.0

### ISSUE THREAD

**Issue by teowenshen** [k2-fsa/icefall#163]
When make_kn_gram.py analyses my transcript_token.txt, either **ZeroDivisionError** occurs at line 244 or **ValueError**: Math domain error occurs at line 353, where sum_z1_f_z became >= 1.0 due to overflow.

> Line 244: `counts_for_hist.word_to_bow[w] = (1.0 - sum_z1_f_a_z) / (1.0 - sum_z1_f_z)`
> Line 353: `line += '\t{0}'.format('%.7f' % math.log10(bow))`

I added an if statement in this program to default my bow to 1e99 if sum_z1_f_z >= 1.0. Is this fail-safe not recommended in general, or is this outlier case simply too rare to be considered ? 

```
>                         if (sum_z1_f_z < 1.0): 
>                             counts_for_hist.word_to_bow[w] = (1.0 - sum_z1_f_a_z) / (1.0 - sum_z1_f_z)
>                         else:
>                             counts_for_hist.word_to_bow[w] = 1e99
```

Background:
I am attempting to create an Icefall recipe for Japanese based on Kaldi-CSJ, Kaldi-LaboroTV and Icefall-AISHELL, so I suspect that the smaller phonetic inventory and stricter phonotactics of Japanese might have caused the polarised backoff weights.

**Comment by pingfengluo** [comment]
maybe your text is empty?

**Comment by teowenshen** [comment]
Actually, on the contrary, my transcript_token.txt contains around 150M worth of text, with only 41 unique tokens. I think that is what caused sum_z1_f_z to become >= 1.0 due to overflow.

**Comment by danpovey** [comment]
I think sum_z1_f_z must be exactly 1.0, perhaps there were no 1-count bigrams so the discounting constant D ends up being 
 0.  This will possibly lead to unexpected things happening due to infinite backoff weights.  I think the easiest fix may be, where it does:
self.d.append(n1 * 1.0 / (n1 + 2 * n2))
we could do
 self.d.append(max(0.01, n1 * 1.0 / (n1 + 2 * n2)))
This should not affect the results measurably since the discounting constant is usually larger than 1.
We should comment that we are doing this to avoid zero discounting constant D, which could happen
if the number of symbols is small and can cause division by zero later on.

@huangruizhe,  perhaps we should make this change in Kaldi as well?

**Comment by huangruizhe** [comment]
I agree with Dan.
With 150M worth of text with only 41 unique tokens, there is chance that all words _w_ in the vocabulary are seen given a certain history _h_. In this case, there is actually no need to compute the back-off-weight (BOW) for _h_, or if we compute the BOW as any value, it will never be used. This case is not considered in the original code. Thanks for raising the issue.

**Comment by danpovey** [comment]
@teowenshen please see whether #168 resolves the issue.

**Comment by teowenshen** [comment]
Hi @danpovey and @huangruizhe , 

Unfortunately, the ZeroDivisionError still happened at the same line, 244, after I removed my workaround. It happened with one of the most common phonemes, /i/. Please see locals() below:- 

> `locals()`
> {'self': <__main__.NgramCounts object at 0x7f56a12aadc0>, 'n': 0, 'this_order_counts': defaultdict(<function NgramCounts.__init__.<locals>.<lambda> at 0x7f56a1013670>, {(): <__main__.CountsForHistory object at 0x7f56a12aa970>, '()': <__main__.CountsForHistory object at 0x7f56a0fbe880>}), 'hist': (), 'counts_for_hist': <__main__.CountsForHistory object at 0x7f56a12aa970>, 'w': 'i', 'a_': ('i',), 'a_counts_for_hist': <__main__.CountsForHistory object at 0x7f56a10160d0>, 'sum_z1_f_a_z': 0.9999963003305069, 'u': 'py', 'sum_z1_f_z': 1.0, '_': (), '_counts_for_hist': <__main__.CountsForHistory object at 0x7f56a12aa970>}

> `p self.d`
> [0, 0.7142857142857143]

FYI, I am making a bigram, so the backoff weights are associated with the unigram. If `d[0] == '0'` is the problem, I noticed that d[0] has been hardcoded to 0 in this snippet below. While I don't understand the additional comment, I am not sure if this current case belongs to the so-called 'other scenarios' because indeed we have seen all 41 tokens in the dictionary. 

>         self.d = [0]  # for the lowest order, i.e., 1-gram, we do not need to discount, thus the constant is 0
>                       # This is a special case: as we currently assumed having seen all vocabularies in the dictionary,
>                       # but perhaps this is not the case for some other scenarios.

Thank you for the verbose explanations. Reading both your comments has helped me more than hours of Googling on my own. 

Please let me know if there is anything more I can provide.

**Comment by huangruizhe** [comment]
Here is my conjecture about the issue: **how comes that _sum_z1_f_z_ still equals 1?**
Two reasons: 

**(1) The set "_Z1_" may equal to the vocabulary** 
Here is how the back-off weight is computed:
<img src="https://render.githubusercontent.com/render/math?math=BOW(h) = \frac{1 - \sum_{z \in Z1} f(h, z)}{1 - \sum_{z \in Z1} f(h', z)}">
where _Z1_ is the set of all words _z_ with _count(h, z)_ > 0 for a given _h_, _h'_ is the history that _h_ backoffs to, and f(h, z) is the discounted probability.
The issue happened in the denominator where we thought <img src="https://render.githubusercontent.com/render/math?math=\sum_{z \in Z1} f(h', z)=1">.

You have 150M worth of text with only 41 unique tokens. So, there is a chance that every word _w_ in the vocabulary is seen after some history _h_, e.g., the phoneme _/i/_. In this case, there is no point to back off for _h_, or we can just assign an arbitrary value to BOW(_h_) as it will never be used -- this is what I did to fix the issue.

Typically, when the vocabulary is large, the _Z1_ for _h_ and the _Z1_ for _h‘_ aren't the same, where the latter is larger, and the two are both strict subset of the vocabulary. So the _sum_z1_f_z_ will always be smaller than 1 for a valid probability distribution, even if the discounting factor is zero.

In your case, it is very likely that _Z1_ equals the vocabulary.

**(2) The discounting factor _d[0]_ is zero for unigrams**
We fixed the case for n>=2 yesterday.
As you noticed, for n=1, it is hardwired as so because we assume that all words seen in the corpus is the vocabulary. Thus there is no unseen unigrams, and so there is no need to discount.
@danpovey Shall we support an option so that the users can specify an external vocabulary?

It is very luck that your specific use case has triggered the two reasons above at the same time..
Let me know if the new PR fixed the problem.

**Comment by huangruizhe** [comment]
PR #168

**Comment by teowenshen** [comment]
Thanks all for your explanation and solution. I will close this issue now.
