### ISSUE TITLE
Som questions about RNNT beam_searh.

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#331]
1、First question is what's the difference between `fast_beam_search()`, `modified_beam_search()` and `beam_search()`, any document or paper discuss the details ?
2、Second question is why the score of new hyp is `new_log_prob = topk_log_probs[k]` rather than `new_log_prob = topk_log_probs[k] + hyp.log_prob` ?
https://github.com/k2-fsa/icefall/blob/d766dc5aeea1a8aefab033e581948b07c4ac4bc0/egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py#L580

**Comment by csukuangfj** [comment]
> 1、First question is what's the difference between fast_beam_search(), modified_beam_search() and beam_search(), any document or paper discuss the details ?

- `fast_beam_search`: Its implementation is in C++ (contained in [k2](https://github.com/k2-fsa/k2/blob/master/k2/csrc/rnnt_decode.h)), supporting using a search graph, e.g., an LG graph.
It produces a lattice and we currently extract the best path from the lattice as the output. Later, we may rescore the lattice with some external LMs.  Different from standard beam search, it assumes that the max sym per frame is 1 and it also assumes that the prediction network, i.e., the decoder model, is stateless.

- `modified_beam_search`: It does not produce a lattice and is not using a search graph.  Similar to `fast_beam_search`, it 
hardcodes the max sym per frame to 1.

- `beam_search`: It is the standard RNN-T beam search, without prefix search. It does not support batch decoding and is rather slow. We don't recommend you to use this decoding method.



> any document or paper discuss the details 

All details are contained in the code. 

There are two submitted papers about the details. Will make them public later.

---

> 2、Second question is why the score of new hyp is new_log_prob = topk_log_probs[k] rather than new_log_prob = topk_log_probs[k] + hyp.log_prob ?

Because it has already been done in the following line:
https://github.com/k2-fsa/icefall/blob/d766dc5aeea1a8aefab033e581948b07c4ac4bc0/egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py#L551

**Comment by kobenaxie** [comment]
Oh, get it, thank you very much ~

**Comment by wgb14** [comment]
Hi. Are you going to publish the papers or preprint of k2 as well as your implementation and modification to RNN-T?

**Comment by csukuangfj** [comment]
>  Hi. Are you going to publish the papers or preprint of k2 as well as your implementation and modification to RNN-T?



Yes, I think so. Maybe in the coming days.
