### ISSUE TITLE
How to finetuning model to recognize english abbreviations? eg: GDP，CPI etc

### ISSUE THREAD

**Issue by shushanxingzhe** [k2-fsa/icefall#405]
@luomingshuang Very thanks for your great work in wenetspeech recipe. The model have archived a good CER, but it is hard to recognize english abbreviations, eg: GDP，CPI etc. Is there any advice to improving it?

**Comment by luomingshuang** [comment]
Thanks for your observation. Yes, in my public recognized results, the English abbreviations still can't be recognized correctly. It's a good question. How to improve the performance of recognizing English abbreviations in Chinese texts. I think there are some reasons leading this case. 
For example, the English abbreviations is `GDPR`, and my recognized results is `极低P而`. Some chinese chars which have the same tone as the English abbreviations mislead the model. 
How to solve this problem is a good topic. Maybe we can leverage the language model or context to relieve it. And maybe others can have more suggestions for this problem.

**Comment by luomingshuang** [comment]
I think one place which can be improved is to do some changes when generate the tokens.txt. In my current, I split the 
proper English abbreviations into individual letters. (GDP-->G D P, generating three tokens: G, D, P.) So one way that we can do is to regard the GDP as a single token, not split it. Maybe I will have some experiments based on this way.

**Comment by shushanxingzhe** [comment]
Very thanks for your reply. I look forward to your release of the new model as I don't have enough hardware to experiment.
