### ISSUE TITLE
A question about the format of load data 

### ISSUE THREAD

**Issue by cdxie** [k2-fsa/icefall#56]
Hi, I am learning the icefall and lhotse recently, and I'm more concerned about the training or testing data processing. The lhotse provides standard data preparation recipes for commonly used corpora, it is very good. I find the lhotse will process the data into JSON format(*.json or *.jsonl.gz), and I also find the lhotse support converting kaldi file to Lhotse manifests. The question I want to know:
1、why select JSON format(*.json or *.jsonl.gz) to represent the data?
2、why not use the kaldi file format(wav.scp,text,utt2dur,.....),I think that it is very clear to know the means

**Comment by csukuangfj** [comment]
I think @pzelasko has something to say about this.

**Comment by pzelasko** [comment]
We originally worked with YAML for better readability but it is much slower to parse due to its syntax. JSON is a standard machine readable format supported by a lot of languages and libraries with very efficient parsers, so it makes Lhotse manifests easier to use with other software and gives us good format support out of the box. 
JSONL is even better as we can easily support streaming reads and writes line by line while keeping the same format for a single item. 

Kaldi data dir is pretty good overall but it’d be difficult to extend for cuts; it was easier to design new manifest types in Python from scratch and add some compatibility with Kaldi.

**Comment by cdxie** [comment]
> We originally worked with YAML for better readability but it is much slower to parse due to its syntax. JSON is a standard machine readable format supported by a lot of languages and libraries with very efficient parsers, so it makes Lhotse manifests easier to use with other software and gives us good format support out of the box.
> JSONL is even better as we can easily support streaming reads and writes line by line while keeping the same format for a single item.
> 
> Kaldi data dir is pretty good overall but it’d be difficult to extend for cuts; it was easier to design new manifest types in Python from scratch and add some compatibility with Kaldi.

Thanks, I got it. 
talking about the Cuts, in the readthedocs of  lhotse, it just tell us how to use, but do not express the concept of using "cuts". So, I want to know the advantage of introducing the cuts into lhotse or some other starting points.

**Comment by pzelasko** [comment]
The main motivation is to have more flexibility in data preparation:
- easily use the acoustic context of an utterance in training
- use multiple utterances (maybe by different speakers) from a dialog as a single example in a batch
- truncate, mix, pad easily
- all related metadata available in the object
- pythonic API
