### ISSUE TITLE
get word confidences 

### ISSUE THREAD

**Issue by himanshucodz55** [k2-fsa/icefall#866]
Hi,
     I am using conformer_ctc and HLG decoding with BPE. I am trying to obtain word confidences, can you please give any leads on this.

**Comment by csukuangfj** [comment]
I would suggest the following steps:

1. Get the boundary of each word (i.e., the start and end frame indexes of each word)
2. Identify the scores of each word by summing the scores belonging to each word. (We use sum because the scores on arcs are in log-domain)


---

Regarding how to get word boundary:
1. You need to have a 1-best path (i.e., an FSA that has only one path)
2. Extract the labels (not aux_labels) of the 1-best path as a 1-D tensor
3. Since you are using BPE, the start frame of a word contains a token starting with the underscore `_`.
4. Since the extracted labels from step 2 contain repeats, you can use them to identify the end frame index of a word
by checking when it switches to a blank token.

**Comment by himanshucodz55** [comment]
Hi,
     Thanks for you reply and explanation. I have done what you have suggested. I extracted word boundaries like this from one of the earlier [threads](https://github.com/k2-fsa/icefall/issues/188) The scores I am getting are in the range of -2 to -11 most of the times. I am applying exponential to convert to confidences ( zero to one) but these confidences are very low even for correct predicted words. If i add these log likelyhood scores of each label the confidence is even going low.  Can you please suggest to make these confidences higher.

**Comment by csukuangfj** [comment]
If you use HLG, I think the final `scores` contains both `am_scores` and `lm_scores`.
Could you first try to subtract `lm_scores` from `scores` and keep only `am_scores`?
