### ISSUE TITLE
num jobs during filter bank calculation

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#924]
Hello,

I see that during filter bank calculation, maximal number of jobs is limited to 15. What is the reason for this limitation?

num_jobs = min(15, os.cpu_count())

Thanks,
AlexG.

**Comment by csukuangfj** [comment]
> I see that during filter bank calculation, maximal number of jobs is limited to 15. What is the reason for this limitation?

You can tune this number by yourself. 

You can use a small number if you only have several CPUs.

**Comment by AlexandderGorodetski** [comment]
On my machine I have 64 CPU's. So can I increase this number to 64 ?

**Comment by csukuangfj** [comment]
I would use 30 or 40. 

It's totally up to you.

Also, note that each job will save features in a separate file, which means the number of generated feature files equals the number of jobs by default. 

The following screenshot is for librispeech train-clean-100. You can see it generates 15 feature files since it is using 15 jobs.

<img width="1111" alt="Screenshot 2023-02-23 at 21 28 06" src="https://user-images.githubusercontent.com/5284924/220920265-b589aac8-f481-49e8-85ba-8e4a913da532.png">

**Comment by jtrmal** [comment]
One reason why the min is that this task can be IO bound.
y.
