### ISSUE TITLE
Streaming vs offline

### ISSUE THREAD

**Issue by Zeiny96** [k2-fsa/icefall#946]
Can we match the results of both stateless7 and stateless7_streaming or at least minimize the difference?

**Comment by maltium** [comment]
As can be seen from the documented results, the chunk size is definitely a factor (320ms vs 640ms). I'm not sure if there's an upper limit, disregarding the effects on latency.

Someone with an understanding of the Zipformer architecture may be able to give an informed answer.

**Comment by yaozengwei** [comment]
The streaming model could only access limited future context because of the causal convolution and chunk-wise attention. 
You could increase the chunk size, to enable the streaming model access more future context for better performance. It would lead to higher latency though.
The difference between the streaming and non-streaming models will be smaller in our upgraded Zipformer. We will release that soon.

**Comment by marcoyang1998** [comment]
You may also use knowledge distillation to improve the performance of streaming Zipformer (stateless7_streaming). Please have a look at https://icefall.readthedocs.io/en/latest/recipes/Non-streaming-ASR/librispeech/distillation.html

**Comment by beyond-boy** [comment]
> 

 upgraded Zipformer can be released in this month(3th)?

**Comment by uni-sagar-raikar** [comment]
@yaozengwei Any updates on the updated Zipformer model release?
